default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: sport_and_training
  database: sport_and_training_development
  password: <%= Rails.application.credentials.dig(:development, :database_password) %>

test:
  <<: *default
  username: sport_and_training
  database: sport_and_training_test
  password: <%= Rails.application.credentials.dig(:test, :database_password) %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: sport_and_training_production
    username: sport_and_training
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: sport_and_training_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sport_and_training_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sport_and_training_production_cable
    migrations_paths: db/cable_migrate
